extends:
  - "airbnb"

rules:
  no-unused-vars:
    - error
    - vars: all
      args: after-used
      argsIgnorePattern: "^_"
      caughtErrorsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  no-underscore-dangle: off
  max-statements-per-line:
    - warn
    - max: 1